Algoritmo "TriangulO"

Var
   b, h, a: real


Inicio
      escreval("------------------------------")
      escreva("Digite a base: ")
      leia(b)
      escreva("Digite a altura: ")
      leia(h)
      escreval("------------------------------")
      a <- (b * h) /2
      escreval("A base é ", b:5:2)
      escreval("A altura é ", h:5:2)
      escreval("O Triangulo é ", a:5:2)
      escreval("------------------------------")
Fimalgoritmo